{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "regions-service.fullname" . }}
type: Opaque
data:
    {{- range .Values.secret }}
    {{ .name }}: {{ .value | b64enc | quote }}
    {{- end }}
{{- end }}